version: "3.7"
services:    
    php-sim:
      image: registry.gitlab.com/infraspeak/web/web-core-api/php:7.4-fpm-dev
      ports: 
        - 8080:8000
      volumes:
        - .:/usr/src/app
      working_dir: /usr/src/app/public
      command: php -S 0.0.0.0:8000